services:
  - type: web
    name: flask-chat
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn --log-level debug -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free